name = "DynamicObjects"
uuid = "23d02862-63fe-4c6e-8fdb-1d52cbbd39d5"
authors = ["Niko Siccha <nikolassiccha@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
