project:
  title: "Examples for DynamicObjects.jl"
  type: website
  output-dir: ../docs/quarto
website:
  sidebar:
    style: "docked"
    contents: auto
jupyter: julia-1.9
execute:
  freeze: auto
  daemon: 999999