# This file is machine-generated - editing it directly is not advised

julia_version = "1.8.2"
manifest_format = "2.0"
project_hash = "468cbf10a89540f625ae30543646923705ecd046"

[[deps.DynamicObjects]]
deps = ["Serialization"]
git-tree-sha1 = "6cf7da05e41f12acdbdd19ca3cc166f96984dcff"
repo-rev = "main"
repo-url = "https://github.com/nsiccha/DynamicObjects.jl"
uuid = "23d02862-63fe-4c6e-8fdb-1d52cbbd39d5"
version = "0.1.3"

[[deps.Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
